//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Appointment
    {
        public int idAppointment { get; set; }
        public int idMedic { get; set; }
        [Required]
        [Display(Name = "Health card number")]
        [RegularExpression("[0-9]{20,20}", ErrorMessage = "The card number must contain exactly 20 digits!")]
        public string cardNumber { get; set; }

        [Required]
        [Display(Name = "Appointment date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> Date { get; set; }

        [Required]
        [Display(Name = "Appointment time")]
        [DataType(DataType.Time)]
        [DisplayFormat(DataFormatString = "{0:hh\\:mm}", ApplyFormatInEditMode = true)]
        public Nullable<System.TimeSpan> Time { get; set; }
        public Nullable<int> idmedicalPrescription { get; set; }


        public virtual Patient Patient { get; set; }
        public virtual Medic Medic { get; set; }
        public virtual medicalPrescription medicalPrescription { get; set; }
    }
}
