//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Assistant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assistant()
        {
            this.Admins = new HashSet<Admin>();
        }
    
        public int idAssistant { get; set; }

        [Display(Name = "First Name*")]
        [Required]
        public string firstName { get; set; }

        [Display(Name = "Last Name*")]
        [Required]
        public string lastName { get; set; }
        public Nullable<int> idMedic { get; set; }

        [Display(Name = "Email*")]
        [DataType(DataType.EmailAddress)]
        [Required]
        public string userName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admin> Admins { get; set; }
        public virtual Medic Medic { get; set; }
    }
}
