//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class medicalPrescription
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public medicalPrescription()
        {
            this.Appointments = new HashSet<Appointment>();
        }
    
        public int idmedicalPrescription { get; set; }


        [Display(Name = "Diagnostic*")]
        [Required]
        public string Diagnostic { get; set; }

        [Display(Name = "Medication*")]
        [Required]
        public string Medication { get; set; }

        [Display(Name = "Free medication*")]
        [Required]
        public bool Free { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
    }
}
