//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC
{
    using System;
    using System.Collections.Generic;
    
    public partial class medicalRecord
    {
        public int idmedicalRecords { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string vaccinations { get; set; }
        public string diseases { get; set; }
        public string previousDiseases { get; set; }
        public string meds { get; set; }
        public string allergies { get; set; }
        public string lastControl { get; set; }
        public string info { get; set; }
        public string cardNumber { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
