//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class medicalRecord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public medicalRecord()
        {
            this.Patients = new HashSet<Patient>();
        }
    
        public int idmedicalRecords { get; set; }

        [Display(Name = "Last control date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> date { get; set; }
        [Display(Name = "Vaccinations")]
        public string vaccinations { get; set; }

        [Display(Name = "Diseases")]
        public string diseases { get; set; }

        [Display(Name = "Previous diseases")]
        public string previousDiseases { get; set; }

        [Display(Name = "Medication")]
        public string meds { get; set; }

        [Display(Name = "Allergies")]
        public string allergies { get; set; }

        [Display(Name = "Last control date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public string lastControl { get; set; }

        [Display(Name = "Another information")]
        public string info { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patient> Patients { get; set; }
    }
}
